-- Create Feedback Table (if it doesn't exist)
create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  type text not null,
  rating integer not null,
  title text not null,
  description text not null,
  email text,
  category text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.feedback enable row level security;

-- Drop policies if they exist to avoid errors when recreating
drop policy if exists "Enable insert for all users" on public.feedback;
drop policy if exists "Enable read access for service role only" on public.feedback;

-- Create Policy to allow anonymous inserts
create policy "Enable insert for all users" on public.feedback for insert with check (true);

-- Create Policy to allow reading only by authenticated users (admins) or service role
create policy "Enable read access for service role only" on public.feedback for select using (auth.role() = 'service_role');
